drivers: soc: glink: remove unused variable "tx_ch_done_info"
../drivers/soc/qcom/glink_loopback_server.c:810:25: error: unused variable 'tx_done_ch_info' [-Werror=unused-variable]
  810 |         struct ch_info *tx_done_ch_info = (struct ch_info *)priv;
      |                         ^~~~~~~~~~~~~~~

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>
Signed-off-by: jaaat4u <devangsingh369@gmail.com>